/.git
/.workbuddy
/system/node_modules/.bin
/website/.git
/website/.openai
/website/.vinext
/website/.wrangler
/website/node_modules/.bin
/website/node_modules/.mf
/website/node_modules/.vite
/website/node_modules/.vite-temp
